### ISSUE TITLE
cuda 矩阵乘法cudaMalloc size 问题

### ISSUE THREAD

**Issue by okesity** [Ewenwan/ShiYanLou#1]
[https://github.com/Ewenwan/ShiYanLou/tree/master/CUDA#11--matrix-multiplication-%E7%9F%A9%E9%98%B5%E4%B9%98%E6%B3%95-%E6%9C%89%E6%97%A0-%E5%85%B1%E4%BA%AB%E5%86%85%E5%AD%98-%E5%AE%9E%E7%8E%B0](url)

源代码为
```	// 分配GPU变量
	cudaMalloc((void **)&d_a,      size*size * sizeof(int));
	cudaMalloc((void **)&d_b,      size*size * sizeof(int));
	cudaMalloc((void **)&d_result, size*size * sizeof(int));
```
而 d_a, d_b, d_result 皆为 float**
不应该是分配 size*size*sizeof(float) 的内存空间吗

**Comment by Ewenwan** [comment]
应该是的，已经修改为float了
